apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appDatabase.name }}-service 
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.appDatabase.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.appDatabase.service.port }} 
      targetPort: {{ .Values.appDatabase.containerPort }}
  selector:
    appName: {{ .Values.appDatabase.name }}  
