namespace: final-project
############################
bdPostgres:
  name: bd-postgres
  replicaCount: 1
  image: postgres:13.13-alpine3.17
  containerPort: 5432
  user: username
  pass: password
  db: mydatabase
  volumeMountName: postgresdata
############################
appContador:
  name: app-contador
  replicaCount: 1
  image: matiops/intro-k8s:app-contador
  containerPort: 8000
  cacheDatabase: redis
  cacheContainerPort: 6379
  cpu:
    request: "250m"
    limit: "500m"
  memory:
    request: "200Mi"
    limit: "2Gi"

  service:
    type: ClusterIP
    port: 8080
############################
appSaludo:
  name: app-saludo
  replicaCount: 1
  image: matiops/intro-k8s:app-saludo
  containerPort: 8000
  cpu:
    request: "250m"
    limit: "500m"
  memory:
    request: "200Mi"
    limit: "2Gi"

  service:
    type: ClusterIP
    port: 8081
############################
ingress:
  rewriteTarget: /$1
  className: nginx
  host: finalproject
  appContador:
    path: /app-contador
    pathType: Prefix
  appSaludo:
    path: /app-saludo(/|$)(.*)
    pathType: ImplementationSpecific
