namespace: final-project
############################
bdPostgres:
  name: bd-postgres
  replicaCount: 1
  image: postgres:13.13-alpine3.17
  containerPort: 5432
  user: username
  pass: password
  db: mydatabase
  volumeMountName: postgresdata

  service:
    type: ClusterIP
    port: 5432
############################
appContador:
  name: app-contador
  replicaCount: 1
  image: matiops/intro-k8s:app-contador
  containerPort: 8000
  cacheDatabase: redis
  cacheContainerPort: 6379
  cpu:
    request: "250m"
    limit: "500m"
  memory:
    request: "200Mi"
    limit: "2Gi"

  service:
    type: ClusterIP
    port: 8080
############################
appSaludo:
  name: app-saludo
  replicaCount: 1
  image: matiops/intro-k8s:app-saludo
  containerPort: 8000
  cpu:
    request: "250m"
    limit: "500m"
  memory:
    request: "200Mi"
    limit: "2Gi"

  service:
    type: ClusterIP
    port: 8081
############################
appDatabase:
  name: app-database
  replicaCount: 1
  image: frangil14/web-service-flask:1.0.0
  containerPort: 5000
  cpu:
    request: "250m"
    limit: "500m"
  memory:
    request: "200Mi"
    limit: "2Gi"

  service:
    type: ClusterIP
    port: 5000

############################
podList:
  name: pod-list
  replicaCount: 1
  image: shayulmer/kubernetes-pods-extractor:latest
  containerPort: 8080
  cpu:
    request: "250m"
    limit: "500m"
  memory:
    request: "200Mi"
    limit: "2Gi"

  service:
    type: ClusterIP
    port: 80

############################
ingress:
  rewriteTarget: /$2
  className: nginx
  host: finalproject
  appContador:
    path: /app-contador
    pathType: Prefix
  podList:
    path: /podList
    pathType: Prefix
  appSaludo:
    path: /app-saludo(/|$)(.*)
    pathType: ImplementationSpecific
  appDatabase:
    path: /app-database(/|$)(.*)
    pathType: ImplementationSpecific
