apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appContador.name }}-service 
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.appContador.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.appContador.service.port }}   # <- Prestar atencion
      targetPort: {{ .Values.appContador.containerPort }}
  selector:
    appName: {{ .Values.appContador.name }} 