apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.podList.name }}-service 
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.podList.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.podList.service.port }} 
      targetPort: {{ .Values.podList.containerPort }}
  selector:
    appName: {{ .Values.podList.name }}