kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.bdPostgres.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.bdPostgres.db | b64enc }}
  POSTGRES_USER: {{ .Values.bdPostgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.bdPostgres.pass | b64enc }}
