kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}-volumen-postgres  
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: {{ .Values.namespace }}-volumen-pv 
  resources:
    requests:
      storage: 1Gi