apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.bdPostgres.name }}-service 
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.bdPostgres.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.bdPostgres.service.port }} 
      targetPort: {{ .Values.bdPostgres.containerPort }}
  selector:
    appName: {{ .Values.bdPostgres.name }}  
